AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics:
  Enabled: false

Layout/LineLength:
  Max: 256
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-capybara
  - rubocop-rspec
