require 'slack-sup/commands/mixins'
require 'slack-sup/commands/help'
require 'slack-sup/commands/about'
require 'slack-sup/commands/subscription'
require 'slack-sup/commands/opt'
require 'slack-sup/commands/set'
require 'slack-sup/commands/stats'
