require 'roar/representer'
require 'roar/json'
require 'roar/json/hal'

require 'slack-sup/api/presenters/paginated_presenter'
require 'slack-sup/api/presenters/status_presenter'
require 'slack-sup/api/presenters/stats_presenter'
require 'slack-sup/api/presenters/round_stats_presenter'
require 'slack-sup/api/presenters/team_presenter'
require 'slack-sup/api/presenters/team_stats_presenter'
require 'slack-sup/api/presenters/teams_presenter'
require 'slack-sup/api/presenters/root_presenter'
require 'slack-sup/api/presenters/user_presenter'
require 'slack-sup/api/presenters/users_presenter'
require 'slack-sup/api/presenters/round_presenter'
require 'slack-sup/api/presenters/rounds_presenter'
require 'slack-sup/api/presenters/sup_presenter'
require 'slack-sup/api/presenters/sups_presenter'
