name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
      - uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: '7.0'
      - uses: browser-actions/setup-geckodriver@latest
        with:
          geckodriver-version: '0.35.0'
      - uses: browser-actions/setup-firefox@v1.5.2
        with:
          firefox-version: '134.0.1'
      - run: |
          bundle install
      - uses: GabrielBB/xvfb-action@v1
        with:          
          run: |
            bundle exec rake spec