name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.7'
          bundler-cache: true
      - uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '5.0'
      - uses: browser-actions/setup-geckodriver@latest
        with:
          geckodriver-version: '0.32.0'
      - uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: '108.0'
      - uses: GabrielBB/xvfb-action@v1
        with:          
          run: |
            bundle exec rake spec
